//
//  SSBitmapFontLabelNode-private.h
//  SSBitmapFont
//
//  Created by Mike Daley on 11/11/2015.
//  Copyright (c) 2015 71Squared Ltd. All rights reserved.
//

@interface SSBitmapFontLabelNode ()


#pragma mark -
#pragma mark Private Methods

/** Creates a new instance of SSBitmapFontNode
 @param     fontDictionary          Dictionary that contains the textures and metric information for the font
 @param     string                  The string to be used when creating the bitmapfont label
 @param     fontFactory             Reference to the font factory that this label was generated by
 @result    New SSBitmapFontNode
 */
- (instancetype)initWithFontDictionary:(NSMutableDictionary *)fontDictionary
                                string:(NSString *)string
                               factory:(SSBitmapFont *)fontFactory;

@end
